sudo: false
language: python
notifications:
  email: false
env:
  - FLASK_VERSION=0.12.2
  - FLASK_VERSION=0.11.1
  - FLASK_VERSION=0.10.1
python:
  - pypy-5.3.1
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install weakrefset; fi
  - pip install Flask==$FLASK_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
